### ISSUE TITLE
TODO notes

### ISSUE THREAD

**Issue by thiagomvas** [thiagomvas/StudyProject#15]
# Calculo
- [x] Limite.md
- [x] Limites Laterais.md
- [x] Limites Laterais Infinitos.md
- [x] Limites Infinitos.md
- [x] Assíntotas.md
- [ ] Calculo de limites por propriedades.md
- [ ] Continuidade.md
- [ ] Listas de exercicios.md
- [ ] Limites no Infinito.md
- [ ] Limites Infinitos no Infinito.md
- [x] Derivadas.md
- [ ] Regra de Derivacao do Produto.md
- [ ] Regra de Derivacao do Quociente.md
- [x] Derivadas Comuns e Regras.md
- [x] Derivação Implicita.md
- [x] Aproximação Linear.md
- [x] Funções Hiperbolicas.md
- [ ] Máximos e Mínimos.md
- [ ] Teorema de Rolle.md
- [ ] Teorema do Valor Médio.md
- [x] Formas Indetermindas.md
- [x] Lei de L'hopital.md
- [ ] Teste da função crescente e decrescente.md
- [ ] Teste da Primeira Derivada.md
- [ ] Teste da Segunda Derivada.md
- [x] Concavidade.md
- [ ] Esboço de gráficos.md
- [ ] Integrais.md
- [x] Primitivas.md
- [ ] Integrais indefinidos.md
- [ ] Integrais definidos.md
- [ ] Teorema Fundamental do Calculo.md
- [ ] Integração por Substituição.md
# Vetores e Geometria Analitica
- [ ] Vetores.md
- [ ] Combinação Linear.md
- [ ] Produto Escalar.md
- [ ] Listas de exercicios.md
- [ ] Produto Vetorial.md
- [ ] Reta.md
- [ ] Planos.md
- [ ] Parabola.md
- [ ] Cônicas.md
- [ ] Circunferencia.md
# Fundamentos Elementares da Matematica
- [ ] Calculo Proposicional.md
- [ ] Equivalência Lógica.md
- [ ] Propriedades de Calculo Proposicional.md
- [ ] Argumentos e Inferência.md
- [ ] Sentenças abertas.md
# Fisica
- [ ] Movimento e velocidade.md
- [ ] Lançamento de projeteis.md
# Algebra Linear
- [ ] Sistemas Lineares.md
